### ISSUE TITLE
Update default look

### ISSUE THREAD

**Issue by Mataniko** [Mataniko/IV-Play#11]
@john-iv I want to update some of the default settings to look a little better for first time runs. Here's a proposed screenshot:

![image](https://cloud.githubusercontent.com/assets/803371/12104475/b8087d5e-b319-11e5-89dd-0c5dc9321de8.png)

**Comment by john-iv** [comment]
Heh, stretching it out to get more text? Is it tough to implement issue #4 which could solve this?  You used to have that functionality in place before making the 50% demarcation for history.dat support.  Can that be conditional and just let the text flow over to the right beyond the 50% line if history.dat is not in the mix?  I typically use 'Normal' art view with my snaps (222x167) and it would benefit having the text flow over in a 800x340 dimensioned IV/Play.

**Comment by Mataniko** [comment]
Should be doable, but haven't looked. My art is set to stretch, so I made the window wide.The font I picked is also wide, but more pleasing than the default. Either way, the green background and Windows XP font needs a small update :)

**Comment by john-iv** [comment]
Well, that's subjective. :) Feel free to update the repo though.
