### ISSUE TITLE
Repo short description trimmed (usage of markdown not allowed).

### ISSUE THREAD

**Issue by klonos** [Mataniko/IV-Play#13]
![ivplay-short_description_trimmed](https://cloud.githubusercontent.com/assets/2423362/13421859/1c028668-dfe5-11e5-858e-2b6f83c2b37c.png)

I'm guessing that you tried copy-pasting the first line of your [README.md](https://github.com/Mataniko/IV-Play/blob/master/README.md) where the `MAME™` part is actually `[MAME](http://www.mamedev.org)™`:

> IV/Play (pronounced ‘Four Play’) is a desktop oriented GUI front-end for **MAME™**.

My guess is that markdown is not permitted for the GitHub repository descriptions and that's why it was trimmed out.

**Comment by Mataniko** [comment]
Thanks, fixed. (Finally!)
