### ISSUE TITLE
[Bug] IV/Play not displaying the missing ROMs dialogue after unsuccessful launch.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#15]
**Steps:**

1. Turn on show errors in F1 configuration screen.
2. Play a game you don't have ROMs for.

**Expected:**
We used to get a dialogue showing the missing items.

**Actual:**
Something flashes but does not show the dialogue any more.

**Comment by Mataniko** [comment]
This is also happening with the current version. I think MAME changed how they report an error back.
