### ISSUE TITLE
[Bug] Major: 1 key is now incorrectly launching games from UI

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#16]
**Steps:**
In UI, highlight game and press 1 key on keyboard.

**Expected:**
Navigate to first game that begins with '1'

**Actual:**
Highlighted game launches.

**User Bad:** If user has gone to another art or DAT view with alt-2, alt-3 etc. they cannot return to first view with alt-1, it launches the game; workaround is art type drop down in F1 screen.

**Comment by Mataniko** [comment]
This was added in the pull request we had, I assume to support launching a game with the default P1 Start button. Removed.
