### ISSUE TITLE
[Bug] Ok out of configuration screen always moves IV/Play to upper left of screen.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#19]
**Steps:**
Launch IV/Play, position onscreen in middle of screen.
Press F1 to go to configuration menu.
Click OK or press ENTER

**Expected:**
F1 configuration screen dismisses and IV/Play remains at its co-ordinates.

**Actual:**
Window is moved up to upper left.

**User Bad:**
After any configuration changes, user then has to go and reposition IV/Play back to where it was.

**Comment by Mataniko** [comment]
Sounds like something's funky with the config file. I can't repro myself. Can you post your cfg file? Try renaming it and then starting iv/play.

**Comment by john-iv** [comment]
Yes, weird, no repro after killing cfg.  Had been doing a lot of testing w/ hidden.ini. Will close, thanks.
