### ISSUE TITLE
Review 2.x.x

### ISSUE THREAD

**Issue by Mataniko** [Mataniko/IV-Play#23]
I've made headway on a complete re-write. It's still very WIP and some features are missing. It's checked in to the 2.x.x branch.

It's probably a good milestone to evaluate whether we want to keep specific features or not.

**Comment by macm2pro** [comment]
I'm very interested!
Is there an exec. available to test?
I'm not a developer and can't compile any code

**Comment by macm2pro** [comment]
I also noticed on github an exec.of latest version is missing while it's present on the website mameui.info

**Comment by retroarchgirl** [comment]
Is the 2.x.x version still being worked on since this is written in 2016!
Or is 1.8.4.0 the current version new features should be added to?

To be very sure: the current github version is 1.8.4.0?

**Comment by john-iv** [comment]
Updates continued on the main branch, have not heard from this branch in 7 years.  Closing.
