### ISSUE TITLE
[Bug] Devices are now displaying in the game list.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#26]
Within the last week or so, alterations in the output of -listxml have broken IV/Play's ability to prevent viewing of the devices class and all 3,900 of them are now showing in the game list.

**Steps:**

1. Use recent daily build of MAME.
2. F5 in IV/Play
3. Observe an item like '10-Bit R-2R DAC', this is a device, doesn't launch and contains partial info on alt-enter.

**Expect:**
Devices to be hidden from display as previously.

**Actual:**
3,900+ devices now show in the UI.  They can't be launched, and they contain partial info when an alt-enter is done on them.

Note: See thread on MW: http://www.mameworld.info/ubbthreads/showflat.php?Cat=&Number=374212&page=0&view=collapsed&sb=5&o=7&fpart=1&vc=1&new=1519827411

**Comment by john-iv** [comment]
Vas seems to indicate in that thread that he only altered -listfull, but I didn't think we used that to populate anything?

**Comment by Mataniko** [comment]
We do use -listfull to populate the quick list, so I added a little more cleanup to make sure devices don't get the the fully updated list. Please test and close if resolved on your end

**Comment by john-iv** [comment]
Looks good, thank you Matan.
