### ISSUE TITLE
[Feature Req.] Allow use of relative paths in IV/Play.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#27]
Currently we utilise the full path to the linked MAME .exe and various support directories in the *.cfg file.

Would request allowing relative paths as well, perhaps even as the default location just as the core MAME.exe does.  So if you launch IV/Play in a directory structure that includes the .exe it shows up as the '.' dot location in the cfg.

I've carted IV/Play and MAME around on a 128G thumb drive and run into this issue when popping into a new computer which assigns a different drive letter.

**Comment by Mataniko** [comment]
This was pretty straightforward to do, I just pushed a commit that adds it but there are probably some use cases I missed.

**Comment by john-iv** [comment]
Relative paths created on .exe from scratch work, thank you!  However, when I hardcoded a path to icons (d:\mame\icons), oddly I then only see the clone icons and not the parents.  The parents take the unavailable white icon.

**Comment by john-iv** [comment]
Ah, looks like you need to have the last slash on icons for it to work, this worked d:\mame\icons\ but this d:\mame\icons did not.

**Comment by Mataniko** [comment]
@john-iv can you test the latest commit?

**Comment by john-iv** [comment]
**Crasher.**
1. Delete IV-play.cfg and *.db.
2. Only have \snap folder in directory structure (no other art types or mameinfo.dat etc.)
3. Re-launch.
4. Quit
5. Launch a second time and press F1 at main UI.

**Expected:**
Brings up config screen w/ only snap in the art folders.

**Actual:**
Assert, then if you bypass that you see a blank config screen with all the art types folders in the well and no options toggled.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at IV_Play.ConfigForm.UpdateArtTypeDropDown()
   at IV_Play.ConfigForm.LoadSettings()
   at IV_Play.ConfigForm.ConfigForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Mataniko** [comment]
I believe I caught all instances of this in the latest commit

**Comment by john-iv** [comment]
Hangs appear to be fixed.
However when launching IV/Play clean (no db no cfg) in the same directory as a mame.exe, after *.cfg is created I see that only the mame.exe is stated as relative in the cfg file.  The other paths are still full paths:
art_view_folders=c:\o\games\mame\snap
bkground_directory=C:\O\Games\MAME\bkground\
icons_directory=C:\O\Games\MAME\icons\
MAME_EXE=.\MAME.exe

**Comment by john-iv** [comment]
Ah, just saw that you addressed this.  Didn't get an email interestingly.  Ok it appears to be fixed thanks!
