### ISSUE TITLE
[Bug] Bkground path in iv-play.cfg loses relative path when image chosen in UI.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#28]
1. Delete iv-play.cfg
2. Start IV/Play.
3. ESC out
4. Check iv-play.cfg, note bkground_directory=.\bkground\
5. This is expected and wanted behavior to make IV-play portable.
6. Launch IV/Play.
7. Hit F1 and click on the bkground image and choose a new one (in the default location from step 4).
8. ESC out
9. Check *.cfg and note that it has now changed to an absolute path even though the image chosen was in the .\bkground directory.

Would suggest only going to an absolute path if image file is in a non-relative directory.  Want to retain the .\bkground\ setting if image file is in .\bkground even if chosen manually.

**Comment by Mataniko** [comment]
I'm pretty sure this was fixed in 9978f5cea914714415cb537fca302ccd69e59024

Either way I can't really reproduce, as I'm getting a rooted path when following the steps. Can you double check you're building the latest version from source and your steps?

**Comment by john-iv** [comment]
I am using 9978f5c.
I should have mentioned that I have the iv-play.exe in the same top level mame directory as the .exe.
When I kill the iv-play.cfg and restart, and then ESC out immediately I get all the paths in the iv-play.cfg as relative as we wanted:
art_view_folders=.\snap\
bkground_directory=.\bkground\
icons_directory=.\icons\
MAME_EXE=.\MAME.exe
bkground_image=Blue Check.png

Do you get that the first time out after a *.cfg rebuild?
The problem comes in the next time I go in and choose a bkground from .\bkground\
upon exit from the app it turns into:
bkground_directory=E:\MAME\Bkground\
bkground_image=800 Orange Red Yellow.png

Does the physical act of choosing a new bkground.png cause the bkground_directory to alter away from .\bkground\ and go to an absolute path?

**Comment by john-iv** [comment]
Also interestingly, if I delete the bkground_directory line completely and then go back in and out to re-create it, it now shows:
bkground_directory=bkground\
Note the lack of the dot.  Weird.  Seems to function though like that.

**Comment by Mataniko** [comment]
This should be fixed in 1683a7125aa6883c5a5c56a222a2165b6a3e4c1d 

The app should now support a mix of both relative and non-relative paths across the board based on where MAME is in relation to the app.

**Comment by Mataniko** [comment]
I think we're overdue for a release. Do you have time to give the README some love? It's a little out of date and missing stuff like Hidden.ini support.

**Comment by john-iv** [comment]
Confirmed fix in today's build.  Thank you. Closing.
