### ISSUE TITLE
background image not retained

### ISSUE THREAD

**Issue by tomcres** [Mataniko/IV-Play#29]
If I choose a new background, it updates the screen and writes the new file name to IV-play.cfg. This is the expected behavior. However, if I close IV/Play and start it again, for some reason it always reverts to the "bkground.png" file and loses the alternative background image that I had previously chosen (and was written to the .cfg file).

**Comment by tomcres** [comment]
Update: I notice that although the IV-play.cfg file still retains the filename of my chosen background image, it seems to ignore it and show bkground.png instead.

**Comment by tomcres** [comment]
I downloaded the source code and while trying to follow the logic of how the background is set, I noticed that I had "rotate background" turned on. Clearing it makes IV/Play start with my chosen background. However, it should be noted that with "rotate background" turned on it _always_ starts with bkground.png rather than choosing a random file from the background directory, so I think this is still a bug.

**Comment by john-iv** [comment]
Hi, I'm having trouble repro-ing your issue.  IV/Play when it creates its first iv-play.cfg file is going to hardcoded default to expecting a background directory called 'bkground' this was in keeping with MAMEUI's historic setup.  It (IV/Play) will also initially look for a bkground.png file in that \bkground directory. (you can delete bkground.png if its actually in there to take it out of the equation if you want. 

That said, you can alter the iv-play.cfg line bkground_directory=.\Bkground\ to equal whatever you want and if you then have the rotate images toggle turned on, it will rotate the images in that named directory.

So to demonstrate, I created a new directory c:\new and put iv-play.exe in it along with mame.exe and create a directory called c:\new\blah and put about 6 *.png files in it.  I ran IV/Play for the first time, it found the mame.exe and built its list.  Now quit out with ESC and look at the new iv-play.cfg.  Yes, you'll see \bkground as the hardcoded expected background directory.  Change that to \blah and make sure rotate_background is true and it will cycle each time IV-Play runs.

That said, if you then launch IV/Play do an F1 and manually choose a new image from elsewhere, it will use that but it will then change your bkground_directory to the location you chose the new image from.  So maybe that's what you're seeing.  So if you keep all your potential backgrounds in a single location you should be fine.

Feel free to write out complete repro steps if you think it warrants it, but it sounds like things are working as designed.

**Comment by john-iv** [comment]
Closing as non-repro.
