### ISSUE TITLE
Votrax verbose output causing Mame/IV/Play to hang/crash.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#31]
With tip of tree from today MAME (which has Aaron's sound system rewrite), if I launch Wizard of Wor (or Qbert) from inside IV/Play and then hit Insert on the demo screen to fast forward the system for 5-10 seconds, it hangs Mame, and the second time it hangs IV/Play requiring killing it in task manager.  Once you kill IV/Play it damages the cfg file and won’t start up again properly.

Running this from built-in MAME UI is fine, running it from commandline is also fine.  Just when in IV/Play.  Note that ‘mame.exe wow -verbose’ shows a ton of Votrax spewage to console.  I think perhaps our ‘listening’ for rom messages and (other output?) from console is being broken by this new debug/verbose spewage. (turning off our ‘show messages’ does not solve the problem, fwiw).  IV/Play doesn’t produce an error log.

1.	Build today’s version of MAME from Git.
2.	Launch IV/Play and use the build above.
3.	Launch Wizard of Wor.
4.	Press Insert on keyboard to fast forward.
5.	On the second speech observe hang in MAME and repeating sounds
6.	Alt-tab out to task manager to kill the MAME process.
7.	If you repeat 2-5 it won’t show MAME in the process list of task manager and you have to kill IV/Play. 
8.	The next time you launch IV/Play it will launch but not display onscreen.

To my knowledge this is the first time that diagnostic information coming out of MAME has caused this kind of crash of both programs.  Is there logic that can be hardened to prevent this breakout?

**Comment by Mataniko** [comment]
I haven't been able to reproduce using MAME built from git yesterday - I assume there was some bug with audio that got fixed - nevertheless I've disabled the stdout redirection in 433ee0a

**Comment by john-iv** [comment]
Yes, I commented that out too when it happened to get around it.  Mamedev may have quieted it further in the ensuing days.  We can close this, thanks.
