### ISSUE TITLE
Update support for new format of history.dat.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#32]
Appears History.dat has gone to XML, requiring front-ends to update to handle the new format.
For the moment they're also providing the old version.

https://www.arcade-history.com/index.php?page=download

**Comment by Mataniko** [comment]
Added in the latest commit, definitely needs more testing

**Comment by john-iv** [comment]
Found an issue, on non-arcade machines (I used the Atari 2600) if you ctrl-PageDown it goes beyond the last line and blanks the box, and you can't ctrl-PageUp to return to the text of the history.

ctrl-down does not appear to have the problem, it stops as expected at the last line.

**Comment by Mataniko** [comment]
This looks like it was an existing bug that we never caught. I redid the whole scrolling routine so everything should be snappy and accurate now.

Scroll up/down now scroll an exact page, where before it used a wrong number to scroll X amount of lines, without accounting for wrapping.

**Comment by john-iv** [comment]
Hi Matan, looks like there are still a few display concerns that may be part of the XML or not.

Using a fresh install of IV/Play w/ default configs I can’t get to the end of some entries, like 005, or Atari 7800 for example.  See pic. Looks like it’s cutting a few lines off.  Doesn’t matter the method to get down there, ctrl-down, ctrl-pagedown, or ctrl-end.

Also I’m getting messages in VS2019 we should upgrade to a newer version of the .NET redist in our builds. Any harm in building to current?

**Comment by Mataniko** [comment]
did you grab the latest commit from this morning - because i can't reproduce.

Updating the .NET version may make us incompatible with Windows 7, so no real reason for us to move.

**Comment by john-iv** [comment]
I did a clone into a new directory and built fresh, it’s this morning’s changes as I don’t have the a2600 problem as originally reported.   Are you using a fresh install with defaults?  Dat font is Segoe UI 10.  I’m now at desktop res of 2560x1440 if that matters.  Here’s my .exe.

**Comment by Mataniko** [comment]
Is your screen hidpi?

**Comment by john-iv** [comment]
I don’t think so.  IV/Play looks closer to my old 1920x1080 setup than it does on my daughters’ Surfaces which are 2736x1824 (where icons and spacing gets wonky).
What resolution are you at?

The problem persists on my 1920x1080 3rd monitor.

**Comment by john-iv** [comment]
Ok, some more info.  I can't repro the issue on my daughter's hidpi Surface at 2736x1824 (005 scrolls and page downs to the end properly).  I do see the problem at 2560x1440 and 1920x1080p.

**Comment by john-iv** [comment]
FWIW, here's another *.dat file that MASH maintains (bugs, driver progress vs. MAME release, etc.).  It's still the old style so it's good to check against the new changes:
https://mameinfo.mameworld.info/

**Comment by Mataniko** [comment]
The old DAT parser is untouched, and still works as is.

I've pushed some more fixes to scrolling that should hopefully handle with some of the edge cases - please try a new build

**Comment by john-iv** [comment]
This is looking good, addresses the issues.  **Question**: I am able to add history.xml and history.dat from the same directory.  Your earlier commit seemed to want to prevent that.  Are they both able to be added?  It appears that you can cycle to each one in the UI, I now have snap, history.xml, mameinfo.dat, and history.dat to choose from.

**Comment by Mataniko** [comment]
It is prevented when we scan the MAME folder, so we don't automatically add both. As a user you are free to add as many different DAT files as you want

**Comment by john-iv** [comment]
Ok, I think this is good to go, thanks.  Do you care to increment the build number and copyright?

**Comment by Mataniko** [comment]
done
