### ISSUE TITLE
[Bug] We don't display the right history.xml entry for some games (clones v. parents)

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#33]
History.dat will reference you to view an original entry that may not be the parent set, but the set referenced still uses the parent entry.

1. Use latest history.xml. https://www.arcade-history.com/index.php?page=download 
2. Go to Donkey Kong US (dkong)
3. Observe history.xml telling you to see the Donkey Kong Japan entry for more info.
4. Go to Donkey Kong Japan (dkongj)
5. Note same info from dkong.

Actually, to put it easier it looks like we're just displaying the history.xml entry for the parent in all the clones, even if the clones have different entries.

**Comment by Mataniko** [comment]
I pushed a fix but also didn't notice you pushed a commit and pushed over it. Looks like it was an update to the README, can you pull the repo again and re-do the change?
