### ISSUE TITLE
feature request: software list support

### ISSUE THREAD

**Issue by arcade-legend** [Mataniko/IV-Play#34]
Hi

Is it possible to add software list support?

It could work like this:
- double click a machine like Atari 2600
- a new window with all supported software list games opens
- you can run the games in this new window

**Comment by john-iv** [comment]
Dupe.

**Comment by arcade-legend** [comment]
Can you explain what "Dupe" means in response to my GREAT feature???

**Comment by Mataniko** [comment]
Regardless of it being a dupe or not, this is not something that I would pursue.

IV/Play was built over 10 years ago, and needs some major rework before any sort of features could be done. We're currently in maintenance mode.

If you'd like to see software list support in IV/Play you are welcome to submit a PR with the feature.
