### ISSUE TITLE
request: Mac version

### ISSUE THREAD

**Issue by ghost** [Mataniko/IV-Play#36]
Hi

For all Mac users it would be nice to have a native Mac exec.
.Net 6.0 is cross platform so I think it's possible.

I now run it through Wine but it's not the ideal situation. However, it works.

**Comment by Mataniko** [comment]
This is pretty much infeasible for a few reasons:

- This will require a rebuild of the entire UI
- It will require targeting .NET Core which last I checked doesn't support generating small executable files, one of the project goals

**Comment by retroarchgirl** [comment]
> This is pretty much infeasible for a few reasons:

Perfectly possible!

> 
>     * This will require a rebuild of the entire UI

Just use Mono to target Mac and Linux. Nothing has to be rebuilded.

https://www.mono-project.com/docs/gui/winforms/porting-winforms-applications/
> 
>     * It will require targeting .NET Core which last I checked doesn't support generating small executable files, one of the project goals

.NET Core even supports MORE features to small executables then standard .NET (like trimming of assemblies) ...

https://gunnarpeipman.com/dotnet-core-self-contained-executable/
