### ISSUE TITLE
request: game info window

### ISSUE THREAD

**Issue by ghost** [Mataniko/IV-Play#38]
Hi

Could there be added an option to display history.xml/game pic in a separate window?
In this way users with multiple monitors can drag this window to another screen.

**Comment by retroarchgirl** [comment]
@john-iv : do you have any interest in this?

**Comment by john-iv** [comment]
Nope.

**Comment by retroarchgirl** [comment]
No problem, it's already in my own frontend I made :) (not publicly available)
If you change your mind, I can use code from my frontend to generate the external window.
