### ISSUE TITLE
Screenshot/Art issue

### ISSUE THREAD

**Issue by MRMIdAS** [Mataniko/IV-Play#43]
So, Screenshots follow the current MAME protocol of being grouped in a folder, based on ROM name, so all your Mortal Kombat screenshots are in a folder called "MK" ETC, however, IV-Play only reads from the SNAP folder, and not from any sub-folders in that directory, as MAMEUI used to.

The result is that to get your handy-dandy screenshots of what this game is and if you've played it before, you have to go in to, say, your Street Fighter 2 folder in SNAP, copy out the screenshot you want, rename it to sf2.png or whatever it would be, all to get the screenshot to display properly.

Needless to say, this probably shouldn't be happening.

**Comment by john-iv** [comment]
Out of scope.
Baseline's screesnhot behaviour changed somewhere along the line since IV/Play was introduced.
Simple solution is just alter mame.ini to:
**snapname %g**
To return to previous behaviour.
