### ISSUE TITLE
[bug] snaps not working

### ISSUE THREAD

**Issue by retroarchgirl** [Mataniko/IV-Play#48]
Not sure what to do to make fricking snaps working, but here they don't work...

I have a folder F:\a and inside is 005.png to test just 1 game

What is wrong in the settings?

![afbeelding](https://user-images.githubusercontent.com/131728750/236295465-311772d2-4c7c-4f7e-a211-d8e885e9475f.png)

So since this snap is not displayed when clicking the game, I can't debug the problem about the file overwriting...

If you click this game, it shoudl display, but it doesn't show anything

![afbeelding](https://user-images.githubusercontent.com/131728750/236295374-8fcdabd1-bd3c-4589-98c1-fc97176a4d31.png)

I use latest github code

**Comment by retroarchgirl** [comment]
I reboot, nothing...

attached is settings file which contains the correct path

[IV-Play.zip](https://github.com/Mataniko/IV-Play/files/11400327/IV-Play.zip)

so yeah, if this is not even working, I cant help you with other problems

**Comment by john-iv** [comment]
You're using art type 'none'. Which as it says, doesn't display anything.

**Comment by retroarchgirl** [comment]
I can choose "none" or "A" LOL :)

![afbeelding](https://user-images.githubusercontent.com/131728750/236296369-1af17d60-be93-4587-9ca0-307ca02010f1.png)

**Comment by john-iv** [comment]
The Art Types are based on whatever you choose to name them, so you can have a large variety named for the directory. Snaps, Titles, Bosses, etc.

![1](https://user-images.githubusercontent.com/9202235/236296671-d7045141-6ad3-4bab-bd36-281f5c5bf051.png)

**Comment by retroarchgirl** [comment]
Ah so that's my folder
ok then
