### ISSUE TITLE
Create anti-favorites, filter out drivers

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#5]
Exclude games from UI somehow, based on list of drivers (to cut all the fruit machines / pinball / gamblers) maybe an anti-favorite.ini with drivers on each line.

**Comment by Mataniko** [comment]
This can be done in a Hidden.ini file, added in commit 6e0626f

I used clrmame to generate a miss list, and used it as is, or users can just add line items manually.It's not by driver, but by set.
