### ISSUE TITLE
Create some sort of image audit to assist with snap/icon creation.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#7]
Possible to do a built in image audit so I can find working games that don't have icons or snaps / and notify me if I have extra icons or snaps for games that don't deserve them (clones, non-working or games that have changed states to non-working or if there are accidental devices or bioses in there).

**Comment by Mataniko** [comment]
This sounds like a good candidate for a separate command line tool or a Python script, but not part of the UI
