### ISSUE TITLE
Maximized IV/Play not repainting UI when ESC'ed out of game.

### ISSUE THREAD

**Issue by john-iv** [Mataniko/IV-Play#8]
Windows 10 Pro x64 (AMD video card) (NVIDIA also reported issue)
1. Launch IV/Play.
2. Maximize IV/Play UI to fullscreen.
3. Launch game.
4. ESC out of game.

Expected:
UI and game list repaint.

Actual:
Blank window seen with IV/Play title-bar across top of monitor, if you hit restore button the UI repaints.

**Comment by Mataniko** [comment]
Fixed in commit 121567c052b0b2f6da7e17ff2fb2d9ce1a30b86f
