### ISSUE TITLE
NullReferenceException in log

### ISSUE THREAD

**Issue by tbayart** [Mataniko/IV-Play#9]
IV/Play try to parse Mame version "0.165" with dot decimal separator but the current culture use comma

In XmlParser, line 56, add IFormatProvider :

float floatMameVersion = float.Parse(Games.MameVersion.Substring(0,5), System.Globalization.CultureInfo.GetCultureInfo("en-US"));

**Comment by Mataniko** [comment]
Thanks, fixed in commit d55286556170d76349117effa393e19a30ca10ae
